name: Build and Upload Go Project for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        go-version: [1.24.3]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build the project
        run: |
          GOOS=${{ matrix.os == 'macos' && 'darwin' || matrix.os == 'windows' && 'windows' || 'linux' }} GOARCH=amd64 go build -o buglang-${{ matrix.os }}${{ matrix.os == 'windows' && '.exe' || '' }} ./cmd/main.go

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: buglang-${{ matrix.os }}${{ matrix.os == 'windows' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}