name: Build and Upload Go Project for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.18, 1.19, 1.20]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build the project
      run: |
        GOOS=${{ matrix.os == 'macos-latest' && 'darwin' || matrix.os == 'windows-latest' && 'windows' || 'linux' }} GOARCH=amd64 go build -o buglang-${{ matrix.os }}-${{ matrix.go-version }} .
      
    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: buglang-${{ matrix.os }}-${{ matrix.go-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}